---
swagger: "2.0"
info:
  description: "A simple service to get cross validation average mean squared error\
    \ of linear regression model built on the 'Advertising' dataset using swagger-2.0\
    \ specification and codegen"
  version: "0.0.1"
  title: "cross_validation_score"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Cloudmesh REST Service for Machine Learning"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /cv:
    get:
      description: "Returns cross validation average mean squared accuracy of linear\
        \ regression model built on the 'Advertising' dataset"
      operationId: "cv_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Mean squared error"
          schema:
            $ref: "#/definitions/CV"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  CV:
    type: "object"
    required:
    - "mse"
    properties:
      mse:
        type: "string"
    example:
      mse: "mse"
