# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CV(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, mse=None):  # noqa: E501
        """CV - a model defined in Swagger

        :param mse: The mse of this CV.  # noqa: E501
        :type mse: str
        """
        self.swagger_types = {
            'mse': str
        }

        self.attribute_map = {
            'mse': 'mse'
        }

        self._mse = mse

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CV of this CV.  # noqa: E501
        :rtype: CV
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mse(self):
        """Gets the mse of this CV.


        :return: The mse of this CV.
        :rtype: str
        """
        return self._mse

    @mse.setter
    def mse(self, mse):
        """Sets the mse of this CV.


        :param mse: The mse of this CV.
        :type mse: str
        """
        if mse is None:
            raise ValueError("Invalid value for `mse`, must not be `None`")  # noqa: E501

        self._mse = mse
