swagger: "2.0"
info: 
  version: "0.0.1"
  title: "SVD on MNIST network"
  description: "REST Service Framework for Singular Value Decomposition on MNIST Image Classification Problem "
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service for Deep Learning"
  license: 
    name: "Apache"
host: "localhost:4874"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /svd:
    get: 
      description: "Display test accuracy of test images on compressed network after applying SVD on the original MNIST network"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Singular Value Decomposition"
          schema: 
            $ref: "#/definitions/SVD"
definitions:
  SVD:
    type: "object"
    required: 
      - "acc"
    properties: 
      acc:
        type: "string"