---
swagger: "2.0"
info:
  description: "REST Service Framework for Singular Value Decomposition on MNIST Image\
    \ Classification Problem "
  version: "0.0.1"
  title: "SVD on MNIST network"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Cloudmesh REST Service for Deep Learning"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /svd:
    get:
      description: "Display test accuracy of test images on compressed network after\
        \ applying SVD on the original MNIST network"
      operationId: "svd_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Singular Value Decomposition"
          schema:
            $ref: "#/definitions/SVD"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  SVD:
    type: "object"
    required:
    - "acc"
    properties:
      acc:
        type: "string"
    example:
      acc: "acc"
